import { MetaDataHeadersRecord } from "../types";

export const globalHeaders: MetaDataHeadersRecord = {
	requestHeaders: [
		"accept",
		"accept-encoding",
		"accept-language",
		"connection",
		"host",
		"priority",
		"sec-fetch-dest",
		"sec-fetch-mode",
		"sec-fetch-site",
		"sec-fetch-user",
		"sec-gpc",
		"upgrade-insecure-requests",
	],
	responseHeaders: [
		"access-control-allow-origin",
		"connection",
		"content-length",
		"content-security-policy",
		"content-type",
		"cross-origin-opener-policy",
		"cross-origin-resource-policy",
		"date",
		"eTag",
		"keep-alive",
		"origin-agent-cluster",
		"referrer-policy",
		"strict-transport-security",
		"vary",
		"x-content-type-options",
		"x-dns-prefetch-control",
		"x-download-options",
		"x-frame-options",
		"x-permitted-cross-domain-policies",
		"x-ratelimit-limit",
		"x-ratelimit-remaining",
		"x-ratelimit-reset",
		"x-xss-protection",
	],
};
